### PR TITLE
Cmake: wrong public macro WEBP_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by FrankXie05**
The wrong include name prevents finding the correct header file path.

Steps to reproduce：
An simple cmake project:

`CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.8)
project(test)
add_executable(main main.cpp)

set(CMAKE_FIND_DEBUG_MODE 1)

find_package(WebP CONFIG REQUIRED)
message(STATUS "WebP Include Dirs: ${WEBP_INCLUDE_DIRS}")
```

The result shows empty even though `config.cmake` is found.
```
  find_package considered the following locations for WebP's Config module:

    F:/update/vcpkg/installed/x64-windows/debug/WebPConfig.cmake
    F:/update/vcpkg/installed/x64-windows/debug/webp-config.cmake
    F:/update/vcpkg/installed/x64-windows/debug/WebPConfig.cmake
    F:/update/vcpkg/installed/x64-windows/debug/webp-config.cmake
    F:/update/vcpkg/installed/x64-windows/WebPConfig.cmake
    F:/update/vcpkg/installed/x64-windows/webp-config.cmake
    F:/update/vcpkg/installed/x64-windows/share/WebP/WebPConfig.cmake

  The file was found at

    F:/update/vcpkg/installed/x64-windows/share/WebP/WebPConfig.cmake

Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)


-- WebP Include Dirs:
-- Configuring done (8.2s)
-- Generating done (0.0s)
-- Build files have been written to: F:/usage/build
```
Related `vcpkg` issue and PR:
https://github.com/microsoft/vcpkg/pull/33212
https://github.com/microsoft/vcpkg/issues/33196

### CODE REVIEW

**Comment by kmilos** [comment]
Should export both `WebP_INCLUDE_DIRS` (canonical) _and_ `WEBP_INCLUDE_DIRS` (compatibility) though.

**Comment by vrabaud** [comment]
Thank you for your patch. This is actually just a mirror. Patches should be submitted as indicated at https://developers.google.com/speed/webp/community
I cherry-picked your patch at:
https://chromium-review.googlesource.com/c/webm/libwebp/+/4868215

**Comment by kmilos** [comment]
Please set the canonical `WebP_INCLUDE_DIRS` as well to match `WebP_LIBRARIES`.

**Comment by vrabaud** [comment]
Done

**Comment by FrankXie05** [comment]
@vrabaud Thank you very much for submitting your work. 
If you need anything from me, please just ask. :)

**Comment by vrabaud** [comment]
:) @FrankXie05 , you are still the author of the commit, I am just the committer in the git history (cf top left of https://chromium-review.googlesource.com/c/webm/libwebp/+/4868215). We obviously keep credit to all our excellent community. Thx! Is there anything we should fix on the CMake side?  Feel free to close the current pull request BTW.

**Comment by FrankXie05** [comment]
I hope this PR will be merged because the repository maintained by our vcpkg is this mirror `webmproject/libwebp`.
https://github.com/microsoft/vcpkg/blob/e8c2a04eb7ca058b6e2f0e6e33c67fdbffeee846/ports/libwebp/portfile.cmake#L3


Should I do this now?


> Please set the canonical `WebP_INCLUDE_DIRS` as well to match `WebP_LIBRARIES`.

**Comment by vrabaud** [comment]
It will be merged, I am just investigating a potential CMake bug on our build farm first.
I already added @kmilos ' s suggestion on the gerrit patch.

**Comment by FrankXie05** [comment]
Strange CLA. 🫤
I have synced your patch content.

**Comment by vrabaud** [comment]
You are the sold author and the CLA check passes for you so it seems fine.

**Comment by vrabaud** [comment]
This has been merged upstream, you can now close this PR. Thx!

**Comment by FrankXie05** [comment]
Thanks a lot. :)

**Pull request closed without merging**
